In [12]:
import numpy as np
import pandas as pd
from sklearn import linear_model
from sklearn.model_selection import train_test_split

In [2]:
data=pd.read_csv('movies.csv')
data

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008
...,...,...,...,...,...,...,...,...
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007
73,A Serious Man,Drama,Universal,64,4.382857,89,$30.68,2009
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011
75,27 Dresses,Comedy,Fox,71,5.343622,40,$160.31,2008
76,(500) Days of Summer,comedy,Fox,81,8.096000,87,$60.72,2009

In [5]:
data.head(10)

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008
5,Water For Elephants,Drama,20th Century Fox,72,3.081421,60,$117.09,2011
6,WALL-E,Animation,Disney,89,2.896019,96,$521.28,2008
7,Waitress,Romance,Independent,67,11.089742,89,$22.18,2007
8,Waiting For Forever,Romance,Independent,53,0.005000,6,$0.03,2011
9,Valentine's Day,Comedy,Warner Bros.,54,4.184038,17,$217.57,2010

In [7]:
a=data['Audience score %'].min(),data['Audience score %'].max()
a

(35, 89)

In [8]:
a=data.describe()
a

       Audience score %  Profitability  Rotten Tomatoes %         Year
count         77.000000      77.000000          77.000000    77.000000
mean          63.727273       4.599483          46.701299  2009.077922
std           13.657113       8.031990          26.095001     1.354974
min           35.000000       0.000000           3.000000  2007.000000
25%           52.000000       1.751351          26.000000  2008.000000
50%           64.000000       2.642353          45.000000  2009.000000
75%           76.000000       5.103117          64.000000  2010.000000
max           89.000000      66.934000          96.000000  2011.000000

In [11]:
x=data[['Film','Genre','Lead Studio','Year','Profitability','Rotten Tomatoes %','Worldwide Gross']]
y=data['Audience score %']
x,y

(                                  Film    Genre            Lead Studio  Year  \
 0           Zack and Miri Make a Porno  Romance  The Weinstein Company  2008
 1                      Youth in Revolt   Comedy  The Weinstein Company  2010
 2   You Will Meet a Tall Dark Stranger   Comedy            Independent  2010
 3                         When in Rome   Comedy                 Disney  2010
 4                What Happens in Vegas   Comedy                    Fox  2008
 ..                                 ...      ...                    ...   ...
 72                 Across the Universe  romance            Independent  2007
 73                       A Serious Man    Drama              Universal  2009
 74                  A Dangerous Method    Drama            Independent  2011
 75                          27 Dresses   Comedy                    Fox  2008
 76                (500) Days of Summer   comedy                    Fox  2009

     Profitability  Rotten Tomatoes % Worldwide Gross
 0        1.747542                 64         $41.94
 1        1.090000                 68         $19.62
 2        1.211818                 43         $26.66
 3        0.000000                 15         $43.04
 4        6.267647                 28        $219.37
 ..            ...                ...             ...
 72       0.652603                 54         $29.37
 73       4.382857                 89         $30.68
 74       0.448645                 79          $8.97
 75       5.343622                 40        $160.31
 76       8.096000                 87         $60.72

 [77 rows x 7 columns],
 0     70
 1     52
 2     35
 3     44
 4     72
       ..
 72    84
 73    64
 74    89
 75    71
 76    81
 Name: Audience score %, Length: 77, dtype: int64)

In [14]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.30)
x_test,y_test,x_train,y_train

(                                   Film      Genre            Lead Studio  \
 51                       License to Wed     Comedy           Warner Bros.
 35                    Not Easily Broken      Drama            Independent
 1                       Youth in Revolt     Comedy  The Weinstein Company
 29               Rachel Getting Married      Drama            Independent
 75                           27 Dresses     Comedy                    Fox
 25                 Sex and the City Two     Comedy           Warner Bros.
 63                   Going the Distance     Comedy           Warner Bros.
 61          He's Just Not That Into You     Comedy           Warner Bros.
 36                      No Reservations     Comedy           Warner Bros.
 53                            Leap Year     Comedy              Universal
 21                     The Back-up Plan     Comedy                    CBS
 9                       Valentine's Day     Comedy           Warner Bros.
 15             The Time Traveler's Wife      Drama              Paramount
 34                              One Day    Romance            Independent
 43                    Midnight in Paris    Romence                   Sony
 39                 My Week with Marilyn      Drama  The Weinstein Company
 71                            Beginners     Comedy            Independent
 23                   Something Borrowed    Romance            Independent
 47                        Made of Honor      Comdy                   Sony
 59            I Love You Phillip Morris     Comedy            Independent
 27                     Sex and the City     Comedy           Warner Bros.
 42       Miss Pettigrew Lives for a Day     Comedy            Independent
 72                  Across the Universe    romance            Independent
 0            Zack and Miri Make a Porno    Romance  The Weinstein Company
 20  The Curious Case of Benjamin Button    Fantasy           Warner Bros.
 70                            Dear John      Drama                   Sony
 44                        Marley and Me     Comedy                    Fox
 24               She's Out of My League     Comedy              Paramount
 32                   Over Her Dead Body     Comedy               New Line
 66           Ghosts of Girlfriends Past     Comedy           Warner Bros.
 7                              Waitress    Romance            Independent
 68                            Fireproof      Drama            Independent
 3                          When in Rome     Comedy                 Disney
 11              Twilight: Breaking Dawn    Romance            Independent
 12                             Twilight    Romance                 Summit
 16                         The Proposal     Comedy                 Disney
 55                              Killers     Action              Lionsgate
 6                                WALL-E  Animation                 Disney
 48                         Love Happens      Drama              Universal
 31                      P.S. I Love You    Romance            Independent
 4                 What Happens in Vegas     Comedy                    Fox
 64                    Gnomeo and Juliet  Animation                 Disney
 69                            Enchanted     Comedy                 Disney
 60   High School Musical 3: Senior Year     Comedy                 Disney
 5                   Water For Elephants      Drama       20th Century Fox
 57                            Jane Eyre    Romance              Universal
 76                 (500) Days of Summer     comedy                    Fox
 28                          Remember Me      Drama                 Summit
 38                       New Year's Eve    Romance           Warner Bros.
 46                           Mamma Mia!     Comedy              Universal
 62                      Good Luck Chuck     Comedy              Lionsgate
 41                          Monte Carlo    Romance       20th Century Fox
 50                   Life as We Know It     Comedy            Independent

     Year  Profitability  Rotten Tomatoes % Worldwide Gross
 51  2007       1.980206                  8         $69.31
 35  2009       2.140000                 34         $10.70
 1   2010       1.090000                 68         $19.62
 29  2008       1.384167                 85         $16.61
 75  2008       5.343622                 40        $160.31
 25  2010       2.883500                 15        $288.35
 63  2010       1.314062                 53         $42.05
 61  2009       7.153600                 42        $178.84
 36  2007       3.307180                 39         $92.60
 53  2010       1.715263                 21         $32.59
 21  2010       2.202571                 20         $77.09
 9   2010       4.184038                 17        $217.57
 15  2009       2.598205                 38        $101.33
 34  2011       3.682733                 37         $55.24
 43  2011       8.744706                 93        $148.66
 39  2011       0.825800                 83          $8.26
 71  2011       4.471875                 84         $14.31
 23  2011       1.719514                 15         $60.18
 47  2008       2.649068                 13        $105.96
 59  2010       1.340000                 71         $20.10
 27  2008       7.221796                 49        $415.25
 42  2008       0.252895                 78         $15.17
 72  2007       0.652603                 54         $29.37
 0   2008       1.747542                 64         $41.94
 20  2008       1.783944                 73        $285.43
 70  2010       4.598800                 29        $114.97
 44  2008       3.746782                 63        $206.07
 24  2010       2.440500                 57         $48.81
 32  2008       2.071000                 15         $20.71
 66  2009       2.044400                 27        $102.22
 7   2007      11.089742                 89         $22.18
 68  2008      66.934000                 40         $33.47
 3   2010       0.000000                 15         $43.04
 11  2011       6.383364                 26        $702.17
 12  2008      10.180027                 49        $376.66
 16  2009       7.867500                 43        $314.70
 55  2010       1.245333                 11         $93.40
 6   2008       2.896019                 96        $521.28
 48  2009       2.004444                 18         $36.08
 31  2007       5.103117                 21        $153.09
 4   2008       6.267647                 28        $219.37
 64  2011       5.387972                 56        $193.97
 69  2007       4.005737                 93        $340.49
 60  2008      22.913136                 65        $252.04
 5   2011       3.081421                 60        $117.09
 57  2011       0.000000                 85         $30.15
 76  2009       8.096000                 87         $60.72
 28  2010       3.491250                 28         $55.86
 38  2011       2.536429                  8        $142.04
 46  2008       9.234454                 53        $609.47
 62  2007       2.367685                  3         $59.19
 41  2011       1.983200                 38         $39.66
 50  2010       2.530526                 28         $96.16   ,
 51    55
 35    66
 1     52
 29    61
 75    71
 25    49
 63    56
 61    60
 36    64
 53    49
 21    47
 9     54
 15    65
 34    54
 43    84
 39    84
 71    80
 23    48
 47    61
 59    57
 27    81
 42    70
 72    84
 0     70
 20    81
 70    66
 44    77
 24    60
 32    47
 66    47
 7     67
 68    51
 3     44
 11    68
 12    82
 16    74
 55    45
 6     89
 48    40
 31    82
 4     72
 64    52
 69    80
 60    76
 5     72
 57    77
 76    81
 28    70
 38    48
 46    76
 62    61
 41    50
 50    62
 Name: Audience score %, dtype: int64,
                                    Film      Genre   Lead Studio  Year  \
 67                     Four Christmases     Comedy  Warner Bros.  2008
 30                             Penelope     Comedy        Summit  2008
 65                    Gnomeo and Juliet  Animation        Disney  2011
 17               The Invention of Lying     Comedy  Warner Bros.  2009
 2    You Will Meet a Tall Dark Stranger     Comedy   Independent  2010
 22                              Tangled  Animation        Disney  2010
 52                    Letters to Juliet     Comedy        Summit  2010
 74                   A Dangerous Method      Drama   Independent  2011
 33                   Our Family Wedding     Comedy   Independent  2010
 58                     It's Complicated     Comedy     Universal  2009
 19                          The Duchess      Drama     Paramount  2008
 45                           Mamma Mia!     Comedy     Universal  2008
 49                   Love & Other Drugs     Comedy           Fox  2010
 14          The Twilight Saga: New Moon      Drama        Summit  2009
 40                     Music and Lyrics    Romance  Warner Bros.  2007
 37   Nick and Norah's Infinite Playlist     Comedy          Sony  2008
 73                        A Serious Man      Drama     Universal  2009
 18                   The Heartbreak Kid     Comedy     Paramount  2007
 10  Tyler Perry's Why Did I get Married    Romance   Independent  2007
 13                       The Ugly Truth     Comedy   Independent  2009
 56                          Just Wright     Comedy           Fox  2010
 54                           Knocked Up     Comedy     Universal  2007
 8                   Waiting For Forever    Romance   Independent  2011
 26                   Sex and the City 2     Comedy  Warner Bros.  2010

     Profitability  Rotten Tomatoes % Worldwide Gross
 67       2.022925                 26        $161.83
 30       1.382800                 52         $20.74
 65       5.387972                 56        $193.97
 17       1.751351                 56         $32.40
 2        1.211818                 43         $26.66
 22       1.365692                 89        $355.01
 52       2.639333                 40         $79.18
 74       0.448645                 79          $8.97
 33       0.000000                 14         $21.37
 58       2.642353                 56        $224.60
 19       3.207850                 60         $43.31
 45       9.234454                 53        $609.47
 49       1.817667                 48         $54.53
 14      14.196400                 27        $709.82
 40       3.647411                 63        $145.90
 37       3.352729                 73         $33.53
 73       4.382857                 89         $30.68
 18       2.129444                 30        $127.77
 10       3.724192                 46         $55.86
 13       5.402632                 14        $205.30
 56       1.797417                 45         $21.57
 54       6.636402                 91           $219
 8        0.005000                  6          $0.03
 26       2.883500                 15        $288.35   ,
 67    52
 30    74
 65    52
 17    47
 2     35
 22    88
 52    62
 74    89
 33    49
 58    63
 19    68
 45    76
 49    55
 14    78
 40    70
 37    67
 73    64
 18    41
 10    47
 13    68
 56    58
 54    83
 8     53
 26    49
 Name: Audience score %, dtype: int64)

In [ ]:
#set-3

In [15]:
data.tail(10)

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
67,Four Christmases,Comedy,Warner Bros.,52,2.022925,26,$161.83,2008
68,Fireproof,Drama,Independent,51,66.934000,40,$33.47,2008
69,Enchanted,Comedy,Disney,80,4.005737,93,$340.49,2007
70,Dear John,Drama,Sony,66,4.598800,29,$114.97,2010
71,Beginners,Comedy,Independent,80,4.471875,84,$14.31,2011
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007
73,A Serious Man,Drama,Universal,64,4.382857,89,$30.68,2009
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011
75,27 Dresses,Comedy,Fox,71,5.343622,40,$160.31,2008
76,(500) Days of Summer,comedy,Fox,81,8.096000,87,$60.72,2009

In [16]:
data.dropna()

,Film,Genre,Lead Studio,Audience score %,Profitability,Rotten Tomatoes %,Worldwide Gross,Year
0,Zack and Miri Make a Porno,Romance,The Weinstein Company,70,1.747542,64,$41.94,2008
1,Youth in Revolt,Comedy,The Weinstein Company,52,1.090000,68,$19.62,2010
2,You Will Meet a Tall Dark Stranger,Comedy,Independent,35,1.211818,43,$26.66,2010
3,When in Rome,Comedy,Disney,44,0.000000,15,$43.04,2010
4,What Happens in Vegas,Comedy,Fox,72,6.267647,28,$219.37,2008
...,...,...,...,...,...,...,...,...
72,Across the Universe,romance,Independent,84,0.652603,54,$29.37,2007
73,A Serious Man,Drama,Universal,64,4.382857,89,$30.68,2009
74,A Dangerous Method,Drama,Independent,89,0.448645,79,$8.97,2011
75,27 Dresses,Comedy,Fox,71,5.343622,40,$160.31,2008
76,(500) Days of Summer,comedy,Fox,81,8.096000,87,$60.72,2009

In [19]:
data.describe()

       Audience score %  Profitability  Rotten Tomatoes %         Year
count         77.000000      77.000000          77.000000    77.000000
mean          63.727273       4.599483          46.701299  2009.077922
std           13.657113       8.031990          26.095001     1.354974
min           35.000000       0.000000           3.000000  2007.000000
25%           52.000000       1.751351          26.000000  2008.000000
50%           64.000000       2.642353          45.000000  2009.000000
75%           76.000000       5.103117          64.000000  2010.000000
max           89.000000      66.934000          96.000000  2011.000000

In [20]:
x=data[['Film','Genre','Lead Studio','Year','Profitability','Rotten Tomatoes %','Worldwide Gross']]
y=data['Audience score %']
x,y

(                                  Film    Genre            Lead Studio  Year  \
 0           Zack and Miri Make a Porno  Romance  The Weinstein Company  2008
 1                      Youth in Revolt   Comedy  The Weinstein Company  2010
 2   You Will Meet a Tall Dark Stranger   Comedy            Independent  2010
 3                         When in Rome   Comedy                 Disney  2010
 4                What Happens in Vegas   Comedy                    Fox  2008
 ..                                 ...      ...                    ...   ...
 72                 Across the Universe  romance            Independent  2007
 73                       A Serious Man    Drama              Universal  2009
 74                  A Dangerous Method    Drama            Independent  2011
 75                          27 Dresses   Comedy                    Fox  2008
 76                (500) Days of Summer   comedy                    Fox  2009

     Profitability  Rotten Tomatoes % Worldwide Gross
 0        1.747542                 64         $41.94
 1        1.090000                 68         $19.62
 2        1.211818                 43         $26.66
 3        0.000000                 15         $43.04
 4        6.267647                 28        $219.37
 ..            ...                ...             ...
 72       0.652603                 54         $29.37
 73       4.382857                 89         $30.68
 74       0.448645                 79          $8.97
 75       5.343622                 40        $160.31
 76       8.096000                 87         $60.72

 [77 rows x 7 columns],
 0     70
 1     52
 2     35
 3     44
 4     72
       ..
 72    84
 73    64
 74    89
 75    71
 76    81
 Name: Audience score %, Length: 77, dtype: int64)

In [18]:
x_test,x_train,y_test,y_train=train_test_split(x,y,test_size=0.25)
x_test,y_test,x_train,y_train

(                                   Film      Genre            Lead Studio  \
 40                     Music and Lyrics    Romance           Warner Bros.
 0            Zack and Miri Make a Porno    Romance  The Weinstein Company
 58                     It's Complicated     Comedy              Universal
 4                 What Happens in Vegas     Comedy                    Fox
 38                       New Year's Eve    Romance           Warner Bros.
 61          He's Just Not That Into You     Comedy           Warner Bros.
 15             The Time Traveler's Wife      Drama              Paramount
 43                    Midnight in Paris    Romence                   Sony
 3                          When in Rome     Comedy                 Disney
 35                    Not Easily Broken      Drama            Independent
 76                 (500) Days of Summer     comedy                    Fox
 64                    Gnomeo and Juliet  Animation                 Disney
 27                     Sex and the City     Comedy           Warner Bros.
 65                    Gnomeo and Juliet  Animation                 Disney
 73                        A Serious Man      Drama              Universal
 23                   Something Borrowed    Romance            Independent
 71                            Beginners     Comedy            Independent
 68                            Fireproof      Drama            Independent
 28                          Remember Me      Drama                 Summit
 7                              Waitress    Romance            Independent
 29               Rachel Getting Married      Drama            Independent
 1                       Youth in Revolt     Comedy  The Weinstein Company
 41                          Monte Carlo    Romance       20th Century Fox
 42       Miss Pettigrew Lives for a Day     Comedy            Independent
 52                    Letters to Juliet     Comedy                 Summit
 50                   Life as We Know It     Comedy            Independent
 10  Tyler Perry's Why Did I get Married    Romance            Independent
 33                   Our Family Wedding     Comedy            Independent
 19                          The Duchess      Drama              Paramount
 17               The Invention of Lying     Comedy           Warner Bros.
 32                   Over Her Dead Body     Comedy               New Line
 55                              Killers     Action              Lionsgate
 44                        Marley and Me     Comedy                    Fox
 54                           Knocked Up     Comedy              Universal
 13                       The Ugly Truth     Comedy            Independent
 57                            Jane Eyre    Romance              Universal
 70                            Dear John      Drama                   Sony
 25                 Sex and the City Two     Comedy           Warner Bros.
 26                   Sex and the City 2     Comedy           Warner Bros.
 21                     The Back-up Plan     Comedy                    CBS
 72                  Across the Universe    romance            Independent
 66           Ghosts of Girlfriends Past     Comedy           Warner Bros.
 59            I Love You Phillip Morris     Comedy            Independent
 11              Twilight: Breaking Dawn    Romance            Independent
 2    You Will Meet a Tall Dark Stranger     Comedy            Independent
 36                      No Reservations     Comedy           Warner Bros.
 18                   The Heartbreak Kid     Comedy              Paramount
 46                           Mamma Mia!     Comedy              Universal
 39                 My Week with Marilyn      Drama  The Weinstein Company
 45                           Mamma Mia!     Comedy              Universal
 20  The Curious Case of Benjamin Button    Fantasy           Warner Bros.
 67                     Four Christmases     Comedy           Warner Bros.
 9                       Valentine's Day     Comedy           Warner Bros.
 69                            Enchanted     Comedy                 Disney
 48                         Love Happens      Drama              Universal
 60   High School Musical 3: Senior Year     Comedy                 Disney
 74                   A Dangerous Method      Drama            Independent

     Year  Profitability  Rotten Tomatoes % Worldwide Gross
 40  2007       3.647411                 63        $145.90
 0   2008       1.747542                 64         $41.94
 58  2009       2.642353                 56        $224.60
 4   2008       6.267647                 28        $219.37
 38  2011       2.536429                  8        $142.04
 61  2009       7.153600                 42        $178.84
 15  2009       2.598205                 38        $101.33
 43  2011       8.744706                 93        $148.66
 3   2010       0.000000                 15         $43.04
 35  2009       2.140000                 34         $10.70
 76  2009       8.096000                 87         $60.72
 64  2011       5.387972                 56        $193.97
 27  2008       7.221796                 49        $415.25
 65  2011       5.387972                 56        $193.97
 73  2009       4.382857                 89         $30.68
 23  2011       1.719514                 15         $60.18
 71  2011       4.471875                 84         $14.31
 68  2008      66.934000                 40         $33.47
 28  2010       3.491250                 28         $55.86
 7   2007      11.089742                 89         $22.18
 29  2008       1.384167                 85         $16.61
 1   2010       1.090000                 68         $19.62
 41  2011       1.983200                 38         $39.66
 42  2008       0.252895                 78         $15.17
 52  2010       2.639333                 40         $79.18
 50  2010       2.530526                 28         $96.16
 10  2007       3.724192                 46         $55.86
 33  2010       0.000000                 14         $21.37
 19  2008       3.207850                 60         $43.31
 17  2009       1.751351                 56         $32.40
 32  2008       2.071000                 15         $20.71
 55  2010       1.245333                 11         $93.40
 44  2008       3.746782                 63        $206.07
 54  2007       6.636402                 91           $219
 13  2009       5.402632                 14        $205.30
 57  2011       0.000000                 85         $30.15
 70  2010       4.598800                 29        $114.97
 25  2010       2.883500                 15        $288.35
 26  2010       2.883500                 15        $288.35
 21  2010       2.202571                 20         $77.09
 72  2007       0.652603                 54         $29.37
 66  2009       2.044400                 27        $102.22
 59  2010       1.340000                 71         $20.10
 11  2011       6.383364                 26        $702.17
 2   2010       1.211818                 43         $26.66
 36  2007       3.307180                 39         $92.60
 18  2007       2.129444                 30        $127.77
 46  2008       9.234454                 53        $609.47
 39  2011       0.825800                 83          $8.26
 45  2008       9.234454                 53        $609.47
 20  2008       1.783944                 73        $285.43
 67  2008       2.022925                 26        $161.83
 9   2010       4.184038                 17        $217.57
 69  2007       4.005737                 93        $340.49
 48  2009       2.004444                 18         $36.08
 60  2008      22.913136                 65        $252.04
 74  2011       0.448645                 79          $8.97   ,
 40    70
 0     70
 58    63
 4     72
 38    48
 61    60
 15    65
 43    84
 3     44
 35    66
 76    81
 64    52
 27    81
 65    52
 73    64
 23    48
 71    80
 68    51
 28    70
 7     67
 29    61
 1     52
 41    50
 42    70
 52    62
 50    62
 10    47
 33    49
 19    68
 17    47
 32    47
 55    45
 44    77
 54    83
 13    68
 57    77
 70    66
 25    49
 26    49
 21    47
 72    84
 66    47
 59    57
 11    68
 2     35
 36    64
 18    41
 46    76
 39    84
 45    76
 20    81
 67    52
 9     54
 69    80
 48    40
 60    76
 74    89
 Name: Audience score %, dtype: int64,
                                   Film      Genre       Lead Studio  Year  \
 63                  Going the Distance     Comedy      Warner Bros.  2010
 56                         Just Wright     Comedy               Fox  2010
 14         The Twilight Saga: New Moon      Drama            Summit  2009
 37  Nick and Norah's Infinite Playlist     Comedy              Sony  2008
 75                          27 Dresses     Comedy               Fox  2008
 62                     Good Luck Chuck     Comedy         Lionsgate  2007
 16                        The Proposal     Comedy            Disney  2009
 30                            Penelope     Comedy            Summit  2008
 49                  Love & Other Drugs     Comedy               Fox  2010
 22                             Tangled  Animation            Disney  2010
 5                  Water For Elephants      Drama  20th Century Fox  2011
 12                            Twilight    Romance            Summit  2008
 31                     P.S. I Love You    Romance       Independent  2007
 47                       Made of Honor      Comdy              Sony  2008
 8                  Waiting For Forever    Romance       Independent  2011
 53                           Leap Year     Comedy         Universal  2010
 24              She's Out of My League     Comedy         Paramount  2010
 34                             One Day    Romance       Independent  2011
 6                               WALL-E  Animation            Disney  2008
 51                      License to Wed     Comedy      Warner Bros.  2007

     Profitability  Rotten Tomatoes % Worldwide Gross
 63       1.314062                 53         $42.05
 56       1.797417                 45         $21.57
 14      14.196400                 27        $709.82
 37       3.352729                 73         $33.53
 75       5.343622                 40        $160.31
 62       2.367685                  3         $59.19
 16       7.867500                 43        $314.70
 30       1.382800                 52         $20.74
 49       1.817667                 48         $54.53
 22       1.365692                 89        $355.01
 5        3.081421                 60        $117.09
 12      10.180027                 49        $376.66
 31       5.103117                 21        $153.09
 47       2.649068                 13        $105.96
 8        0.005000                  6          $0.03
 53       1.715263                 21         $32.59
 24       2.440500                 57         $48.81
 34       3.682733                 37         $55.24
 6        2.896019                 96        $521.28
 51       1.980206                  8         $69.31   ,
 63    56
 56    58
 14    78
 37    67
 75    71
 62    61
 16    74
 30    74
 49    55
 22    88
 5     72
 12    82
 31    82
 47    61
 8     53
 53    49
 24    60
 34    54
 6     89
 51    55
 Name: Audience score %, dtype: int64)

In [ ]:
#set-2